const INDUSTRY_LABELS_EN: Record<string, string> = {
  "半导体": "Semiconductors",
  "消费电子": "Consumer Electronics",
  "光学光电子": "Optoelectronics",
  "通信设备": "Telecom Equipment",
  "IT服务": "IT Services",
  "软件开发": "Software Development",
  "计算机设备": "Computer Equipment",
  "自动化设备": "Automation Equipment",
  "其他电子": "Other Electronics",
  "元件": "Components",
  "文化传媒": "Cultural Media",
  "影视院线": "Film & Cinema",
  "游戏": "Gaming",
  "通信服务": "Telecom Services",
  "通用设备": "General Equipment",
  "专用设备": "Specialized Equipment",
  "电机": "Electric Motors",
  "工程机械": "Construction Machinery",
  "轨交设备": "Rail Transit Equipment",
  "化学制药": "Chemical Pharma",
  "生物制品": "Biologics",
  "中药": "Traditional Chinese Medicine",
  "医疗器械": "Medical Devices",
  "医疗服务": "Healthcare Services",
  "医药商业": "Pharmaceutical Distribution",
  "白酒": "Baijiu",
  "饮料制造": "Beverage Manufacturing",
  "食品加工制造": "Food Processing & Manufacturing",
  "白色家电": "White Goods",
  "黑色家电": "Brown Goods",
  "小家电": "Small Home Appliances",
  "厨卫电器": "Kitchen & Bathroom Appliances",
  "服装家纺": "Apparel & Home Textiles",
  "纺织制造": "Textile Manufacturing",
  "家居用品": "Home Furnishings",
  "包装印刷": "Packaging & Printing",
  "造纸": "Paper Making",
  "种植业与林业": "Planting & Forestry",
  "农产品加工": "Agricultural Products Processing",
  "养殖业": "Aquaculture & Livestock",
  "旅游及酒店": "Tourism & Hotels",
  "零售": "Retail",
  "互联网电商": "E-commerce",
  "贸易": "Trading",
  "教育": "Education",
  "美容护理": "Beauty Care",
  "其他社会服务": "Other Social Services",
  "综合": "Conglomerates",
  "汽车整车": "Automobiles",
  "汽车零部件": "Auto Parts",
  "汽车服务及其他": "Auto Services & Others",
  "电池": "Batteries",
  "风电设备": "Wind Power Equipment",
  "光伏设备": "Photovoltaic Equipment",
  "其他电源设备": "Other Power Equipment",
  "军工电子": "Defense Electronics",
  "军工装备": "Defense Equipment",
  "化学原料": "Chemical Raw Materials",
  "化学制品": "Chemical Products",
  "化学纤维": "Chemical Fibers",
  "农化制品": "Agrochemical Products",
  "塑料制品": "Plastic Products",
  "橡胶制品": "Rubber Products",
  "石油加工贸易": "Petroleum Processing & Trading",
  "油气开采及服务": "Oil & Gas Exploration Services",
  "工业金属": "Industrial Metals",
  "小金属": "Minor Metals",
  "贵金属": "Precious Metals",
  "能源金属": "Energy Metals",
  "非金属材料": "Non-metallic Materials",
  "建筑材料": "Building Materials",
  "燃气": "Gas Utilities",
  "环保设备": "Environmental Equipment",
  "环境治理": "Environmental Governance",
  "建筑装饰": "Building Decoration",
  "房地产": "Real Estate",
  "电网设备": "Grid Equipment",
  "钢铁": "Steel",
  "电力": "Power Utilities",
  "银行": "Banks",
  "证券": "Brokers",
  "保险": "Insurance",
  "多元金融": "Diversified Financials",
  "港口航运": "Port & Shipping",
  "公路铁路运输": "Road & Rail Transport",
  "机场航运": "Airport & Aviation",
  "物流": "Logistics",
  "煤炭开采加工": "Coal Mining & Processing",
  "金属新材料": "Advanced Metal Materials",
  "电子化学品": "Electronic Chemicals",
  "有色金属": "Nonferrous Metals",
}

const SECTOR_LABELS_EN: Record<string, string> = {
  "科技": "Technology",
  "医药": "Healthcare",
  "消费": "Consumer",
  "汽车": "Automotive",
  "新能源": "New Energy",
  "军工": "Defense",
  "原材料": "Materials",
  "公用事业和基建": "Utilities & Infrastructure",
  "金融": "Financials",
  "交运物流": "Transportation & Logistics",
}

function isEnglishLocale(locale: string) {
  return locale.toLowerCase().startsWith("en")
}

export function getLocalizedIndustryName(industry: string, locale: string) {
  if (!isEnglishLocale(locale)) return industry
  return INDUSTRY_LABELS_EN[industry] || industry
}

export function getLocalizedSectorName(sector: string, locale: string) {
  if (!isEnglishLocale(locale)) return sector
  return SECTOR_LABELS_EN[sector] || sector
}
